[book]
authors = ["Tomo"]
language = "en"
multilingual = false
src = "src/"
title = "unicornpkg specification"
[output.html]
git-repository-url = "https://github.com/unicornpkg/spec"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/unicornpkg/spec/edit/main/{path}"
site-url = "/spec/"
